flowchart TD
  app_agent_runtime --> app_agent_kernel
  app_agent_runtime --> app_agent_tools
  app_agent_runtime --> app_physics_parser
  app_agent_runtime --> app_physics_problem_frame
  app_agent_tools --> app_physics_method_search
  app_agent_tools --> app_physics_parser
  app_agent_tools --> app_physics_problem_frame
  app_agent_tools --> app_physics_unit_converter
  app_eval_explanation_metrics --> app_explanation_worker
  app_eval_explanation_metrics --> app_schemas
  app_eval_scorers --> app_physics_qualitative_normalizer
  app_eval_scorers --> app_physics_unit_converter
  app_eval_scorers --> app_schemas
  app_explanation_worker --> app_physics_formulas
  app_explanation_worker --> app_schemas
  app_logic__fol_bridge --> app_logic__proof_classes
  app_logic__fol_bridge --> app_logic__rule_matcher
  app_logic__fol_bridge --> app_logic__subject_chain
  app_logic__fol_bridge --> app_logic__text_primitives
  app_logic__fol_bridge --> app_logic_premise_selector
  app_logic__fol_bridge --> app_logic_proof_trace
  app_logic__fol_bridge --> app_logic_templates
  app_logic__fol_bridge --> app_schemas
  app_logic__mcq_solver --> app_logic__fol_bridge
  app_logic__mcq_solver --> app_logic__proof_classes
  app_logic__mcq_solver --> app_logic__question_parser
  app_logic__mcq_solver --> app_logic__rule_matcher
  app_logic__mcq_solver --> app_logic__subject_chain
  app_logic__mcq_solver --> app_logic__text_primitives
  app_logic__mcq_solver --> app_logic_premise_selector
  app_logic__mcq_solver --> app_logic_proof_trace
  app_logic__mcq_solver --> app_schemas
  app_logic__proof_classes --> app_logic_premise_selector
  app_logic__proof_classes --> app_logic_proof_trace
  app_logic__proof_classes --> app_schemas
  app_logic__question_parser --> app_logic__text_primitives
  app_logic__rule_matcher --> app_logic__proof_classes
  app_logic__rule_matcher --> app_logic__text_primitives
  app_logic__rule_matcher --> app_logic_premise_selector
  app_logic__subject_chain --> app_logic__proof_classes
  app_logic__subject_chain --> app_logic__question_parser
  app_logic__subject_chain --> app_logic__rule_matcher
  app_logic__subject_chain --> app_logic__text_primitives
  app_logic__subject_chain --> app_logic_premise_selector
  app_logic__subject_chain --> app_logic_proof_trace
  app_logic__subject_chain --> app_schemas
  app_logic__text_primitives --> app_logic_premise_selector
  app_logic_agent_runtime --> app_agent_kernel
  app_logic_agent_runtime --> app_logic_agent_tools
  app_logic_agent_runtime --> app_logic_premise_selector
  app_logic_agent_tools --> app_logic_policy_reasoner
  app_logic_agent_tools --> app_logic_premise_selector
  app_logic_agent_tools --> app_logic_templates
  app_logic_fol_z3_pipeline --> app_explanation_worker
  app_logic_policy_reasoner --> app_logic_policy_patterns
  app_logic_policy_reasoner --> app_logic_premise_selector
  app_logic_policy_reasoner --> app_logic_thresholds
  app_logic_proof_trace --> app_logic_premise_selector
  app_logic_solver --> app_guardrails
  app_logic_solver --> app_logic__fol_bridge
  app_logic_solver --> app_logic__mcq_solver
  app_logic_solver --> app_logic__proof_classes
  app_logic_solver --> app_logic__question_parser
  app_logic_solver --> app_logic__rule_matcher
  app_logic_solver --> app_logic__subject_chain
  app_logic_solver --> app_logic__text_primitives
  app_logic_solver --> app_logic_agent_runtime
  app_logic_solver --> app_logic_policy_reasoner
  app_logic_solver --> app_logic_premise_selector
  app_logic_solver --> app_logic_proof_trace
  app_logic_solver --> app_logic_templates
  app_logic_solver --> app_schemas
  app_logic_templates --> app_logic_policy_patterns
  app_logic_templates --> app_logic_premise_selector
  app_logic_templates --> app_logic_thresholds
  app_main --> app_env
  app_main --> app_router
  app_physics_adapters_base --> app_physics_equation_graph
  app_physics_adapters_base --> app_physics_ir
  app_physics_adapters_circuit --> app_physics_adapters_base
  app_physics_adapters_circuit --> app_physics_circuit_solver
  app_physics_adapters_circuit --> app_physics_equation_graph
  app_physics_adapters_circuit --> app_physics_ir
  app_physics_adapters_circuit --> app_physics_unit_converter
  app_physics_adapters_electrostatics --> app_physics_adapters_base
  app_physics_adapters_electrostatics --> app_physics_equation_graph
  app_physics_adapters_electrostatics --> app_physics_ir
  app_physics_adapters_electrostatics --> app_physics_scene_parser
  app_physics_adapters_measurement --> app_physics_adapters_base
  app_physics_adapters_measurement --> app_physics_equation_graph
  app_physics_adapters_measurement --> app_physics_ir
  app_physics_adapters_measurement --> app_physics_unit_converter
  app_physics_adapters_mechanics --> app_physics_adapters_base
  app_physics_adapters_mechanics --> app_physics_dimensions
  app_physics_adapters_mechanics --> app_physics_equation_graph
  app_physics_adapters_mechanics --> app_physics_ir
  app_physics_adapters_mechanics --> app_physics_unit_converter
  app_physics_adapters_registry --> app_physics_adapters_base
  app_physics_adapters_registry --> app_physics_adapters_circuit
  app_physics_adapters_registry --> app_physics_adapters_electrostatics
  app_physics_adapters_registry --> app_physics_adapters_measurement
  app_physics_adapters_registry --> app_physics_adapters_mechanics
  app_physics_equation_graph --> app_physics_dimensions
  app_physics_expression_eval --> app_physics_formulas
  app_physics_ir --> app_physics_dimensions
  app_physics_ir --> app_physics_unit_converter
  app_physics_method_search --> app_physics_expression_eval
  app_physics_method_search --> app_physics_formulas
  app_physics_method_search --> app_physics_parser
  app_physics_parser --> app_physics_expression_eval
  app_physics_parser --> app_physics_qualitative_parser
  app_physics_parser --> app_physics_unit_converter
  app_physics_problem_frame --> app_physics_parser
  app_physics_qualitative_reasoner --> app_physics_qualitative_normalizer
  app_physics_scene_parser --> app_physics_dimensions
  app_physics_scene_parser --> app_physics_formulas
  app_physics_scene_parser --> app_physics_unit_converter
  app_physics_solver --> app_agent_runtime
  app_physics_solver --> app_guardrails
  app_physics_solver --> app_physics
  app_physics_solver --> app_physics_adapters_base
  app_physics_solver --> app_physics_adapters_registry
  app_physics_solver --> app_physics_dimensions
  app_physics_solver --> app_physics_expression_eval
  app_physics_solver --> app_physics_formula_registry
  app_physics_solver --> app_physics_formulas
  app_physics_solver --> app_physics_ir
  app_physics_solver --> app_physics_method_search
  app_physics_solver --> app_physics_parser
  app_physics_solver --> app_physics_problem_frame
  app_physics_solver --> app_physics_qualitative_normalizer
  app_physics_solver --> app_physics_qualitative_parser
  app_physics_solver --> app_physics_scene_parser
  app_physics_solver --> app_physics_templates
  app_physics_solver --> app_physics_unit_converter
  app_physics_solver --> app_schemas
  app_physics_templates --> app_physics_formulas
  app_physics_templates --> app_physics_unit_converter
  app_router --> app_llm_client
  app_router --> app_logic_premise_selector
  app_router --> app_logic_proof_trace
  app_router --> app_logic_solver
  app_router --> app_physics_solver
  app_router --> app_pipeline_config
  app_router --> app_runtime_clients
  app_router --> app_runtime_trace
  app_router --> app_runtime_workflow
  app_router --> app_schemas
  app_runtime_clients --> app_llm_client
  app_runtime_clients --> app_pipeline_config
  app_runtime_trace --> app_confidence
  app_runtime_trace --> app_explanation_worker
  app_runtime_trace --> app_llm_client
  app_runtime_trace --> app_logic_premise_selector
  app_runtime_trace --> app_runtime_workflow
  app_runtime_trace --> app_schemas
  app_runtime_workflow --> app_guardrails
  app_runtime_workflow --> app_schemas
